#!/usr/bin/env python3
"""Generate Data/sheet-specs/<sheet>.build.md stubs for every plan sheet.

Skips referenceLibrary sheets. Does not overwrite 619-311.build.md or any
existing playbook that already has a '# ' title (unless --force).
Also sets sheet.buildGuide in the JSON when missing.
"""
from __future__ import annotations

import argparse
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
SPEC_DIR = ROOT / "Data" / "sheet-specs"

TEMPLATE = """# {number} — live build playbook

Durable tips for **{title}**. Machine prefs live in `{number}.json`
(`annotationStyle`, channelizing `representation`, `annotations`, `rules`).
Extend this file when a live build surfaces a gotcha — do not leave tips
only in `dev-notes/agent-log.md`.

**Authority:** official NYSDOT PDF → this sheet JSON → this playbook → chat hints.

Source: see `sheet.sourceUrl` / `sheet.localPdf` in `{number}.json`.

---

## Preferred call path

1. Collect designer inputs (do not invent) — see `inputs` / `applicability` in the JSON.
2. `get_sheet_requirements("{number}")` — read `buildGuide` on the response.
3. `build_wztc_order_table(..., sheet_num="{number}", ...)` — show the walk.
4. Point-pick upstream then downstream work-area edges.
5. Prefer `run_sheet_build(upstream_edge, downstream_edge)`.
6. For cheap try→score→KEEP/REVERT: `begin_sheet_sandbox` / `run_sheet_build_sandbox`
   then `keep_sheet_sandbox` or `revert_sheet_sandbox` (offset Y band; does not
   wipe the kept corridor).
7. On ERROR: `phases[].replan` / `reflect_sheet_build` — do not full-restart.
8. Confirm `get_geometry_scorecard().passed` (geometry-faithful), review QA
   frames (vision-attached), then FINAL.

---

## Machine preferences

Follow `{number}.json` `annotationStyle` and `symbols` representation when
present. Compiler path (`place_sheet_geometry`) is required when this JSON
exists — heuristic `place_order_table_*` only with `force=True`.

---

## Visual QA

- Scorecard + automated visual rules must pass before scripted captures count.
- Chat agent: `run_visual_qa_captures` attaches frames as vision + SCREENSHOT.
- Do not call `capture_view` (MCP-only); use `view_drawing` for ad-hoc looks.

---

## Sheet-specific tips

_(Append live gotchas below.)_

- Stub generated by `scripts/generate_sheet_build_guides.py`. Replace this
  bullet with real tips after the first successful live build.
"""


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--force", action="store_true",
                    help="Overwrite existing .build.md (except keep richer 311)")
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    created = 0
    updated_json = 0
    skipped = 0
    for path in sorted(SPEC_DIR.glob("619-*.json")):
        raw = json.loads(path.read_text(encoding="utf-8"))
        sheet = raw.get("sheet") or {}
        if sheet.get("kind") == "referenceLibrary":
            skipped += 1
            continue
        number = sheet.get("number") or path.stem
        title = sheet.get("title") or number
        guide_name = sheet.get("buildGuide") or f"{number}.build.md"
        guide_path = SPEC_DIR / pathlib.Path(guide_name).name

        # Never clobber the hand-authored 619-311 playbook unless --force
        # and even then require explicit --force-311
        if number == "619-311" and guide_path.exists() and not args.force:
            # Still ensure pointer
            if not sheet.get("buildGuide"):
                sheet["buildGuide"] = "619-311.build.md"
                raw["sheet"] = sheet
                if not args.dry_run:
                    path.write_text(json.dumps(raw, indent=2) + "\n", encoding="utf-8")
                updated_json += 1
            skipped += 1
            continue

        body = TEMPLATE.format(number=number, title=title)
        write_md = args.force or not guide_path.exists()
        if write_md:
            if not args.dry_run:
                guide_path.write_text(body, encoding="utf-8")
            created += 1

        if sheet.get("buildGuide") != guide_path.name:
            sheet["buildGuide"] = guide_path.name
            raw["sheet"] = sheet
            if not args.dry_run:
                path.write_text(json.dumps(raw, indent=2) + "\n", encoding="utf-8")
            updated_json += 1

    print(f"created_or_refreshed_md={created} json_buildGuide_set={updated_json} skipped={skipped}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
